### ISSUE TITLE
Render deprecated fields with a line through them

### ISSUE THREAD

**Issue by AOrobator** [JetBrains/js-graphql-intellij-plugin#312]
## Version and Environment Details
__Operation system__: Mac OS X 10.15.1

__IDE name and version__: Android Studio 3.5.3

__Plugin version__: v2.3.0

## Expected Behaviour
When a field in graphql is annotated with `deprecated` I'd like for the IDE to strike a line through deprecated usages in queries, mutations, and fragments.

## Actual Behaviour
No indication of deprecation

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Use this type in your schema

```graphql
type ExampleEntity {
  exampleDeprecatedField: Int! @deprecated(reason : "This is deprecated")
}
```

**Comment by AOrobator** [comment]
@jimkyndemeyer I would like to get started on this issue. Do you have any pointers for how I can get started or what files to modify?

**Comment by SriwanKm** [comment]
One year later and still I wish this issue would get reopened.  I might try again but I recall getting lost in a maze of Plugin files because i wasn't so used to doing PSI stuff. This seems like a super useful feature. Currently we use a python reporting script to generate Jira tickets for deprecations, but directly in IDE with a line through it and an inspection would be much easier to maintain and integrate nicely with CI tools. Let me know if anyone has some free time to pair code this one out

**Comment by amerryma** [comment]
HI @vepanimas were you able to take a look at this yet?

**Comment by vepanimas** [comment]
Finally, I was able to work on that. Feel free to try it in the latest 2024.1 EAP2 of the WebStorm, IDEA, or any other compatible IDE. More details are [here](https://youtrack.jetbrains.com/issue/WEB-63597/GraphQL-mark-deprecated-items-as-strikethrough-text#focus=Change-27-8961466.0-0).
