### ISSUE TITLE
.graphqlconfig has no code highlighting and no arrow icon buttons to fetch schema next to line numbers

### ISSUE THREAD

**Issue by simPod** [JetBrains/js-graphql-intellij-plugin#482]
**Describe the bug**

I have `.graphqlconfig` file present in several projects but the plugin does not show arrows next to endpoint to fetch schema

**To Reproduce**
Link to Repo with Reproduction or Steps to Reproduce:
1. Go to 'https://github.com/simPod/js-graphql-gradle-bug (#423)
2. Click on '.graphqlconfig file
4. See no controls added, no highlighting enabled. It's displayed as a simple text file

It can find endpoints though:

![image](https://user-images.githubusercontent.com/327717/127893097-51b69467-903c-4dab-b705-20ae295eb6c7.png)

**Expected behavior**

E.g. show play arrow icon to create schema file and highlight the json

**Screenshots**

![image](https://user-images.githubusercontent.com/327717/127892077-d38d564a-0891-4a36-89a2-8cf5a7213c5c.png)

**Version and Environment Details**
Operation system: macos latest
IDE name and version: 2021.2
Plugin version: 3.0.0

**Comment by vepanimas** [comment]
Hi! Thank you for the report. I also noticed this behavior after upgrading to 3.0, but I decided that it was an accident due to active testing and experimenting with the settings. When building a plugin from the source code, unfortunately, I can't reproduce it. I'll try to take a closer look.

To fix it locally you could try to add file association manually like on the screenshot below:

![json-file-type](https://user-images.githubusercontent.com/10243762/127919411-5ab02b7a-787b-4f3d-9e5b-ccebd99e6dea.png)

**Comment by vepanimas** [comment]
Perhaps this https://youtrack.jetbrains.com/issue/IDEA-274889 is the reason.

**Comment by simPod** [comment]
Thank you. Yes, added json type "fixes" the highlighting :)

**Comment by simPod** [comment]
And it also fixed the missing arrow button. So the problem is somehow the registration of the `.graphqlconfig` extension.

**Comment by alex-grover** [comment]
this issue also just popped up for me after a recent update. perhaps it's worth pinning this issue as it was not immediately clear from the title that it actually fixes broken syntax highlighting outside of the `.graphqlconfig` file as well.

**Comment by simPod** [comment]
I have not encountered this problem for some time.
