### ISSUE TITLE
Problem with multiple projects in the same workspace

### ISSUE THREAD

**Issue by l0co** [JetBrains/js-graphql-intellij-plugin#660]
When using this plugin with multiple projects in a single workspace:

1. Plugin complaints about re-declaring the same type, regardless they are defined in other projects and not re-declared in the same project.
2. When you navigate to a given type (GOTO - CTRL+B in linux), plugin can navigate to type with the same name located in a different project.

To reproduce, please create an empty workspace, add two projects, add two schemas in these two separated projects, and add types with the same name to both schemas.

**Comment by vepanimas** [comment]
@l0co Unfortunately, there are not enough details to understand what's going on. Could you please share your GraphQL config? How do you configure those two projects to separate type definitions from each other?

**Comment by l0co** [comment]
Under a single workspace you can have multiple projects from different git roots using File | New | Module from existing sources. Eg:

1. Create a java project
2. Create another java problem in a different/new workspace
3. In second java project use "Module from existing source" to add a first project to the workspace.

Another way:
1. Create a new project/workspace
2. To the root project dir copy a few other projects (they will be discovered by idea as separate modules)
3. You now have multi-project workspace

**Comment by vepanimas** [comment]
The plugin works with "scopes," which can be either global (including every GraphQL file under the project root) or restricted by a configuration file. It doesn't consider module structure and relies on the filesystem because it's IDE-agnostic. For example, IDEA/Android Studio, WebStorm, and Rider have significantly different project models.

The easiest way in your case is to create an empty `graphql.config.yml` in every separate module you need.
